Repository GSG-FC02/E-Electronics-01, pull requests merged in 2021-03, with the labels that each got.

#5 file-structure
  aboutus.html
  index.html
  style.css
Labels: awaiting review

#11 add navbar
  index.html
  style.css
Labels: awaiting review

#12 add header
  images/Google Home.webp
  images/collection.webp
  images/headphones.webp
  images/phone.webp
  images/xbox.webp
  index.html
  style.css
Labels: awaiting review

#13 add most popular product
  index.html
  style.css
Labels: awaiting review

#17 add about us
  aboutus.html
  images/about-img.jpg
  images/headphone1.PNG
  images/lab-tea.jpg
  images/lap-headphone.PNG
  images/large-speaker.PNG
  images/lcd.PNG
  images/m-headphone.PNG
  images/music-player.PNG
  images/small-speaker.PNG
  index.html
  style.css
Labels: awaiting review

#21 add responsive to page one
  images/promotion_600x.jpg
  index.html
  style.css
Labels: awaiting review

#22 Add Footer
  aboutus.html
  images/Kipsch.jpg
  images/LG.jpg
  images/harman-kardon.jpg
  images/jbl.jpg
  images/pioneer.jpg
  images/sony.jpg
  index.html
  style.css
Labels: approved

#23 update navbar
  aboutus.html
  images/eicon.png
  images/elogo.png
  index.html
  style.css
Labels: done

#24 update responsive
  style.css
Labels: awaiting review

#27 26 last submit
  aboutus.html
  index.html
  style.css
Labels: awaiting review
